satellite:
  katello_ca_rpm: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
  org: prod
  activationkey: gpte-labs-rhel8

postgres_databases:
  - name: flask_db
    owner: flask
  - name: books_store
    owner: flask

postgres_users:
  - name: flask
    password: redhat
    database: flask_db
    state: present
    priv: ALL
